### ISSUE TITLE
Cleanup Analyze Reactions Page - W21 Epic: Slack Data Collection/Analytics

### ISSUE THREAD

**Issue by avatarmiko** [ucsb-cs156-w21/proj-mapache-search#170]
# Epic

This ticket is a sub-ticket created from #146 

# User Story

As a member/admin I can view the Analyze Reactions page data in a clean and user friendly format so that I know which users are making the reactions and can search more easily

# Acceptance Criteria

- [ ] Users show up as their profile names rather than user id in the User column as well as in the text field
- [ ] Links are clickable
- [ ] Bonus: emoji image preview is shown next to text in search bar and/or in text field of table

# Implementation Todos

Front end:

- [ ] Refer to #147 to make links clickable
- [ ] Replace user id with profile full name
- [ ] Create react component to map emoji names to emoji images to insert in the page

Testing:

- [ ] Check correct user name displayed
- [ ] Check links are clickable and take you to the right place
- [ ] Check emojis printed correctly
