### ISSUE TITLE
Count Messages By User Page - W21 Epic: Slack Data Collection/Analytics

### ISSUE THREAD

**Issue by avatarmiko** [ucsb-cs156-w21/proj-mapache-search#171]
# Epic

This ticket is a sub-ticket created from #146 

# User Story

As a member/admin I can see how many messages have been sent by each user in the slack workspace so that I can see the level of participation in the class.

# Acceptance Criteria

- [x] Correct number of messages displayed per user (there are currently duplicates, these should be eliminated - this also needs to happen in all other message analytics pages so feel free to collaborate with ppl working on those pages)
- [x] Table is sortable for increasing/decreasing amount of messages + alphabetical order of users

# Implementation Todos

Front end:

- [x] Display table with Users and MessageCount with Bootstrap table

Back end:

- [x] Get all messages from api/memebers/messages/allmessages and increase corresponding sender's message count
- [x] Get all slack users from api/slackUsers

Testing:

- [x] Check that correct number of messages are being reported by backend
- [x] Check that all users exist in the table

**Comment by avatarmiko** [comment]
branch: 6pm-2-messages-histogram
the name of the branch is weird beacause i created it for ticket #136 but realized i needed to fix this one first ¯\_(ツ)_/¯
