### ISSUE TITLE
Individual Channels Pages - W21 Epic: Slack Data Collection/Analytics

### ISSUE THREAD

**Issue by avatarmiko** [ucsb-cs156-w21/proj-mapache-search#174]
# Epic
This ticket is a sub-ticket created from #146

# User Story

As a member/admin I can view which users are sending messages by name and view channels in list view so that I know which students are sending messages and can search them easily.

# Acceptance Criteria

- [x] List view page renders and does not "go blank"
- [x] Senders always show up by their profile name rather than their user id
- [ ] Search feature works in list view and brings up relevant messages in that channel

# Implementation Todos

Front end:

- [x] Add a check to see if data has been loaded before accessing its properties, this should eliminate the issue with the page going blank 
- [ ] Print bootstrap table of all relevant messages from the api in list view when a search is done
- [x] Replace user id with user profile name

Back end:

- [ ] Get messages from api/members/messages/allmessages and filter by messages in a particular channel and then by the search criteria in the search bar in list view

Testing:

- [ ] Check that user id's are not printed
- [ ] Check that relevant messages are printed in the table when a search is done in list view
- [ ] Check that all pages render and stay rendered
